{{- range $name, $item := .Values.services }}
---
{{ include "nuc-knative.renderResource" (dict
  "root" $
  "item" $item
  "resourceName" $name
  "kind" "Service"
  "defaultApiVersion" $.Values.apiVersions.service
  "resourceKey" "services"
  "namespaced" true
) }}
{{- end }}
