{{- range $index, $item := .Values.services }}
---
{{ include "nuc-knative.renderResource" (dict
  "root" $
  "item" $item
  "kind" "Service"
  "defaultApiVersion" $.Values.apiVersions.service
  "resourceKey" (printf "services[%d]" $index)
  "namespaced" true
) }}
{{- end }}
